title: Marla Brizel
description: Code and stuff and things from a newbie developer

url: http://www.marlabrizel.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: marlabrizel
   twitter: marlabrizel

google_analytics: "UA-48000406-1"

exclude: [vendor]
