title: Marla Brizel
description: Code and stuff and things from a newbie developer

url: http://blog.marlabrizel.com
baseurl: ""
paginate_path: "page:num/"
permalink: :title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about

social:
   github: marlabrizel
   twitter: marlabrizel

google_analytics: "UA-48000406-1"

exclude: [vendor]
